stages:
  - test

variables:
  NODE_VERSION: "16"
  ENV: "UAT"  # Default environment

test:
  stage: test
  image: mcr.microsoft.com/playwright:latest  # Use the latest version available
  script:
    - npm ci  # Install all dependencies
    - npx tsc  # Compile TypeScript
    - npx playwright install --with-deps  # Ensure Playwright browsers are installed
    - export ENV=${CI_ENVIRONMENT_NAME:-${ENV}}
    - npx playwright test --grep-invert @Fail
  artifacts:
    paths:
      - playwright-report/
    expire_in: 1 week
  when: manual
  only:
    - branches

