variables:
  ENV: "UAT" # Default environment

default:
  tags:
    - dind # This triggers the docker runner to pick up the job

stages:
  - test

test:
  stage: test
  only:
    - merge_requests
  image: mcr.microsoft.com/playwright:latest # Use the latest version available
  script:
    - npm ci # Install all dependencies
    - npx tsc # Compile TypeScript
    - npx playwright install --with-deps # Ensure Playwright browsers are installed
    - echo "ENV=$ENV" > .env # Create dotenv file
    - npx playwright test --grep-invert @Fail
  artifacts:
    name: playwright-artifacts
    paths:
      - playwright-report
      - test-results
    expire_in: 1 week