name: Github CI

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'UAT'
        type: choice
        options:
          - SIT
          - UAT
  pull_request:
    branches:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Set environment variable
      run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
    - name: Compile TypeScript
      run: npx tsc

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '16' # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Set environment variable
      run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
    
    - name: Compile TypeScript
      run: npx tsc
    
    - name: Run tests
      run: npx playwright test --grep-invert @Fail
      env:
        # LOG_LEVEL: ${{ inputs.logLevel }}
        # TEST_TAGS: ${{ inputs.tags }}
        ENV: ${{ inputs.environment }}
        
    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-report
        path: playwright-report/playwright-report-*/** # Use wildcard to match all files in the dynamic directory
