name: Test
run-name: Test Executed by @${{ github.actor }} on ${{ inputs.environment }} environment

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'UAT'
        type: choice
        options:
          - SIT
          - UAT

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '16' # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm ci

    - name: Compile TypeScript
      run: npx tsc
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Set environment variable
      run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
    
    - name: Run tests
      run: npx playwright test --grep-invert @Fail
      env:
        # LOG_LEVEL: ${{ inputs.logLevel }}
        # TEST_TAGS: ${{ inputs.tags }}
        ENV: ${{ inputs.environment }}
        
    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-html-report
        path: playwright-report/playwright-report-*/** # Use wildcard to match all files in the dynamic directory
        


      # logLevel:
      #   description: 'Log level'
      #   required: true
      #   default: 'warning'
      #   type: choice
      #   options:
      #     - info
      #     - warning
      #     - debug
      # tags:
      #   description: 'Test scenario tags'
      #   required: true
      #   type: string

# name: CI Workflow

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Environment to run tests against'
#         required: false
#         default: 'UAT'
#         type: choice
#         options:
#           - SIT
#           - UAT
#   pull_request:
#     branches:
#       - main  # Specify the branches you want to trigger the compile job on pull requests

# jobs:
#   compile:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - uses: actions/setup-node@v4
#       with:
#         node-version: '16' # Specify the Node.js version you want to use

#     - name: Install dependencies
#       run: npm ci

#     - name: Compile TypeScript
#       run: npx tsc

#     # Save compiled files as artifacts for the test job
#     - name: Upload compiled artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: compiled-code
#         path: dist/ # Assuming compiled files are in the 'dist' directory

#   test:
#     runs-on: ubuntu-latest
#     needs: compile # Ensure this job runs after the compile job
#     if: github.event_name == 'workflow_dispatch' # Only run on workflow_dispatch

#     steps:
#     - uses: actions/checkout@v4

#     - uses: actions/setup-node@v4
#       with:
#         node-version: '16'

#     # Download compiled artifacts from the compile job
#     - name: Download compiled artifacts
#       uses: actions/download-artifact@v4
#       with:
#         name: compiled-code

#     - name: Install Playwright browsers
#       run: npx playwright install --with-deps

#     - name: Set environment variable
#       run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV

#     - name: Run tests
#       run: npx playwright test --grep-invert @Fail
#       env:
#         ENV: ${{ inputs.environment }}

#     - name: Upload Playwright HTML report
#       uses: actions/upload-artifact@v4
#       with:
#         name: playwright-html-report
#         path: playwright-report/playwright-report-*/** # Use wildcard to match all files in the dynamic directory