name: Execute Tests
run-name: Test Executed by @${{ github.actor }} on ${{ inputs.environment }} environment

on: 
  workflow_dispatch:
    inputs:
      # logLevel:
      #   description: 'Log level'
      #   required: true
      #   default: 'warning'
      #   type: choice
      #   options:
      #     - info
      #     - warning
      #     - debug
      # tags:
      #   description: 'Test scenario tags'
      #   required: true
      #   type: string
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'SIT'
        type: choice
        options:
          - SIT
          - UAT

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '16' # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Set environment variable
      run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
    
    - name: Compile TypeScript
      run: npx tsc
    
    - name: Run tests
      run: npx playwright test --grep-invert @Fail
      # env:
        # LOG_LEVEL: ${{ inputs.logLevel }}
        # TEST_TAGS: ${{ inputs.tags }}
        # ENV: ${{ inputs.environment }}
        
    - name: Upload Playwright HTML report
      uses: actions/upload-artifact@v3
      with:
        name: index.html
